name: five-minute-cron

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch:        # allow manual run

jobs:
  call-endpoints:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: five-minute-cron
      cancel-in-progress: false   # avoid overlapping runs

    steps:
      - name: Hit rate-limit-cleanup endpoint
        run: |
          set -euo pipefail
          URL="https://ingepro.app/api/cron/rate-limit-cleanup"
          echo "Hitting $URL"
          curl --fail --silent --show-error \
               --max-time 50 \
               --retry 3 --retry-all-errors --retry-delay 5 \
               -H "User-Agent: gh-five-minute-cron" \
               "$URL"
